resolver: lts-14.15

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- show-type-0.1.1
- git: https://github.com/int-index/caps.git
  commit: ab4345eabd58fc6f05d3b46bea2c5acdba3ec6f8
# tezos-bake-monitor-lib and its deps which are used in morley-client
- git:
    https://gitlab.com/obsidian.systems/tezos-bake-monitor-lib.git
  commit:
    19a9ce57a0510bc3ad8a3f639d0a968a65024b86
  subdirs:
    - tezos-bake-monitor-lib
- functor-infix-0.0.5@sha256:cea21a321031f556d7a21b51e049493e7cb78baf64dd63f0d1a36de01c4c735b
- hashing-0.1.0.1@sha256:98861f16791946cdf28e3c7a6ee9ac8b72d546d6e33c569c7087ef18253294e7
- dependent-sum-0.6.2.0
- dependent-sum-template-0.1.0.0
- constraints-extras-0.3.0.2@sha256:bf6884be65958e9188ae3c9e5547abfd6d201df021bff8a4704c2c4fe1e1ae5b
- morley-1.0.0
- morley-prelude-0.3.0@sha256:9e9473ac14cfa206adf0a3700764c0251de05042f1fe45daf9cb8556079ae663,2085

#   # morley-1.0.0 doesn't come with a version of morley-ledgers on hackage
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    55db70779cc6ea3eb8507752b1397f3f602eb9c5 # 1.0.0
  subdirs:
    # - .
    # - prelude
    # - morley-upgradeable
    # - morley-ledgers
    # - morley-ledgers-test
    # - indigo
    # - morley-nettest

    # - .
    # - prelude
    - tasty-hunit-compat
    - morley-upgradeable
    - morley-ledgers
    - morley-ledgers-test
    - morley-multisig
    - morley-lorentz
    - indigo
    - morley-nettest
    - morley-client

nix:
  shell-file: shell.nix
